#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediaAndroidTest.Resource", IsApplication=true)]

namespace MediaAndroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_action_icon_size = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int notification_action_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_big_circle_margin = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int notification_large_icon_height = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_large_icon_width = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int notification_right_icon_size = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int notification_small_icon_background_padding = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_small_icon_size_as_large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_subtext_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_top_pad = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_top_pad_large_text = 2131165203;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000f
			public const int MyButton = 2131361807;
			
			// aapt resource value: 0x7f0a0014
			public const int action_container = 2131361812;
			
			// aapt resource value: 0x7f0a0020
			public const int action_divider = 2131361824;
			
			// aapt resource value: 0x7f0a0015
			public const int action_image = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int action_text = 2131361814;
			
			// aapt resource value: 0x7f0a0021
			public const int actions = 2131361825;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int button1 = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int button2 = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int button3 = 2131361811;
			
			// aapt resource value: 0x7f0a001f
			public const int chronometer = 2131361823;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0018
			public const int icon = 2131361816;
			
			// aapt resource value: 0x7f0a0022
			public const int icon_group = 2131361826;
			
			// aapt resource value: 0x7f0a0011
			public const int imageView1 = 2131361809;
			
			// aapt resource value: 0x7f0a001b
			public const int info = 2131361819;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a001d
			public const int notification_background = 2131361821;
			
			// aapt resource value: 0x7f0a0019
			public const int notification_main_column = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int notification_main_column_container = 2131361815;
			
			// aapt resource value: 0x7f0a001c
			public const int right_icon = 2131361820;
			
			// aapt resource value: 0x7f0a001a
			public const int right_side = 2131361818;
			
			// aapt resource value: 0x7f0a000e
			public const int switch_cancel = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int switch_front = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int switch_save_album = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int switch_size = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a001e
			public const int time = 2131361822;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_template_custom_big = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_icon_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_part_chronometer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int file_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
