#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediaAndroidTest.Resource", IsApplication=true)]

namespace MediaAndroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int button1 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int button2 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int button3 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int imageView1 = 2130837508;
			
			// aapt resource value: 0x7F020000
			public const int MyButton = 2130837504;
			
			// aapt resource value: 0x7F020005
			public const int switch_cancel = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int switch_front = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int switch_save_album = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int switch_size = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F050000
			public const int file_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
